
services:
  rvc2mqtt:
    container_name: rvc2mqtt
    build: .
    environment:
      - CAN_INTERFACE_NAME=can1
      - FLOORPLAN_FILE_1=/floorplan/2023_entegra_ethos_20DL.yml
      - FLOORPLAN_FILE_2
      - LOG_CONFIG_FILE=/config/logger.yml
      - MQTT_HOST=localhost
      - MQTT_PORT=1883
      - MQTT_USERNAME
      - MQTT_PASSWORD
      - MQTT_CLIENT_ID
    network_mode: "host"
    restart: on-failure
    volumes:
      - ./floorplan:/floorplan
      - ./config:/config
      - ./logs:/logs

  mosquitto:
    image: eclipse-mosquitto:2.0.18-openssl
    restart: on-failure
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./logs:/mosquitto/log
      - ./data:/mosquitto/data
      - ./config:/mosquitto/config
